export const givingCopy = {
    fr: {
        eyebrow: "Semer dans le Royaume",
        title: "Votre générosité transforme des vies.",
        intro: "Chaque don soutient l’annonce de l’Évangile, les actions de compassion et la mission de NBY — Cité du Surnaturel.",
        verse: "Que chacun donne comme il l’a résolu en son cœur.",
        reference: "2 Corinthiens 9:7",
        formEyebrow: "Faire un don",
        formTitle: "Choisissez votre offrande",
        donationType: "Nature de votre contribution",
        donationTypes: ["Don financier", "Don en nature", "Temps & compétences"],
        donationTypeHelp: [
            "Contribuez par Mobile Money, carte ou virement.",
            "Offrez des vivres, vêtements, équipements ou fournitures.",
            "Mettez votre disponibilité ou votre savoir-faire au service de la mission.",
        ],
        designation: "Affectation du don",
        designations: ["Dîme", "Offrande", "Mission", "Action sociale", "Construction"],
        frequency: "Fréquence",
        once: "Une fois",
        monthly: "Chaque mois",
        amount: "Montant",
        other: "Saisissez le montant",
        itemCategory: "Catégorie du don",
        itemCategories: ["Parcelle / bien immobilier", "Vivres", "Vêtements", "Matériel", "Fournitures", "Autre"],
        itemDescription: "Décrivez ce que vous souhaitez offrir",
        itemPlaceholder: "Décrivez le don. Pour une parcelle : localisation, superficie et documents disponibles.",
        landLocation: "Localisation de la parcelle",
        landArea: "Superficie approximative",
        landDocuments: "Documents disponibles",
        skillCategory: "Domaine de service",
        skillCategories: ["Accueil", "Musique", "Communication", "Technique", "Santé", "Enseignement", "Autre"],
        skillDescription: "Parlez-nous de votre disponibilité ou compétence",
        skillPlaceholder: "Ex. disponible le samedi, photographie, sonorisation…",
        contactLabel: "Vos coordonnées",
        namePlaceholder: "Nom complet",
        phonePlaceholder: "Téléphone / WhatsApp",
        currency: "Devise",
        payment: "Moyen de paiement",
        methods: ["Mobile Money", "Carte bancaire", "Virement"],
        continue: "Continuer en toute sécurité",
        submitting: "Enregistrement…",
        submitInKind: "Proposer ce don",
        submitSkill: "Proposer mon aide",
        notice: "Aucun paiement ne sera débité à cette étape.",
        pendingTitle: "Contribution enregistrée",
        pendingText: "Votre intention de contribution a été transmise à l’équipe NBY. Aucun paiement n’a été débité à cette étape ; nous vous contacterons pour la suite.",
        proposalReady: "Merci pour votre générosité. Votre proposition a été transmise à l’équipe NBY, qui vous contactera pour organiser la réception.",
        close: "Modifier mon don",
        impactEyebrow: "Pourquoi donner ?",
        impactTitle: "Une offrande, plusieurs vies touchées",
        impacts: [
            ["Évangélisation", "Porter la Parole et le message du surnaturel au-delà de nos murs."],
            ["Compassion", "Accompagner les familles et les personnes traversant des moments difficiles."],
            ["Édification", "Créer des espaces de prière, d’enseignement et de transformation."],
        ],
        trust: "Votre don compte",
        trustText: "NBY s’engage à administrer chaque contribution avec fidélité, responsabilité et transparence.",
    },
    en: {
        eyebrow: "Sow into the Kingdom",
        title: "Your generosity transforms lives.",
        intro: "Every gift supports the Gospel, compassion initiatives and the mission of NBY — City of the Supernatural.",
        verse: "Each of you should give what you have decided in your heart.",
        reference: "2 Corinthians 9:7",
        formEyebrow: "Give",
        formTitle: "Choose your offering",
        donationType: "Type of contribution",
        donationTypes: ["Financial gift", "In-kind donation", "Time & skills"],
        donationTypeHelp: [
            "Contribute by Mobile Money, card or bank transfer.",
            "Give food, clothing, equipment or supplies.",
            "Offer your availability or expertise to support the mission.",
        ],
        designation: "Gift designation",
        designations: ["Tithe", "Offering", "Mission", "Social action", "Building"],
        frequency: "Frequency",
        once: "One time",
        monthly: "Monthly",
        amount: "Amount",
        other: "Enter the amount",
        itemCategory: "Donation category",
        itemCategories: ["Land / real estate", "Food", "Clothing", "Equipment", "Supplies", "Other"],
        itemDescription: "Describe what you would like to give",
        itemPlaceholder: "Describe the gift. For land: location, area and available documents.",
        landLocation: "Land location",
        landArea: "Approximate area",
        landDocuments: "Available documents",
        skillCategory: "Service area",
        skillCategories: ["Welcome", "Music", "Communication", "Technical", "Health", "Teaching", "Other"],
        skillDescription: "Tell us about your availability or skill",
        skillPlaceholder: "E.g. available Saturdays, photography, sound engineering…",
        contactLabel: "Your details",
        namePlaceholder: "Full name",
        phonePlaceholder: "Phone / WhatsApp",
        currency: "Currency",
        payment: "Payment method",
        methods: ["Mobile Money", "Bank card", "Bank transfer"],
        continue: "Continue securely",
        submitting: "Saving…",
        submitInKind: "Offer this donation",
        submitSkill: "Offer my help",
        notice: "No payment will be charged at this step.",
        pendingTitle: "Contribution recorded",
        pendingText: "Your contribution intent was sent to the NBY team. No payment was charged at this step; we will contact you about the next step.",
        proposalReady: "Thank you for your generosity. Your offer was sent to the NBY team, who will contact you to arrange it.",
        close: "Edit my gift",
        impactEyebrow: "Why give?",
        impactTitle: "One offering, many lives touched",
        impacts: [
            ["Evangelism", "Carry the Word and the message of the supernatural beyond our walls."],
            ["Compassion", "Support families and people going through difficult seasons."],
            ["Discipleship", "Create spaces for prayer, teaching and transformation."],
        ],
        trust: "Your gift matters",
        trustText: "NBY is committed to stewarding every contribution with faithfulness, accountability and transparency.",
    },
} as const;

export type GivingCopy = (typeof givingCopy)[keyof typeof givingCopy];
