"use client";

import { FormEvent, useRef, useState } from "react";
import { Check, ChevronLeft, ChevronRight, Megaphone, Target, X } from "lucide-react";
import { motion } from "framer-motion";
import { plainText, publicApi, type PublicCampaign } from "@/lib/church-api";

export default function GivingCampaigns({ campaigns, locale }: { campaigns: PublicCampaign[]; locale: "fr" | "en" }) {
    const [selected, setSelected] = useState<PublicCampaign | null>(null);
    const [sent, setSent] = useState(false);
    const [error, setError] = useState("");
    const trackRef = useRef<HTMLDivElement>(null);
    if (!campaigns.length) return null;
    const fr = locale === "fr";
    async function submit(event: FormEvent<HTMLFormElement>) {
        event.preventDefault();
        if (!selected) return;
        const form = new FormData(event.currentTarget);
        setError("");
        try {
            await publicApi("/public/pledges", { method: "POST", body: JSON.stringify({ campaignId: selected.id, subscriberName: form.get("name"), phone: form.get("phone"), pledgedAmount: Number(form.get("amount")), currency: selected.currency, dueDate: form.get("dueDate") || undefined, status: "pending" }) });
            setSent(true);
        } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "Enregistrement impossible."); }
    }
    const scroll = (direction: -1 | 1) => trackRef.current?.scrollBy({ left: direction * Math.min(trackRef.current.clientWidth * .82, 760), behavior: "smooth" });
    return <section className="overflow-hidden bg-[#071117] px-5 py-20 text-white sm:px-8"><div className="mx-auto max-w-[1160px]"><div className="flex items-end justify-between gap-6"><div><p className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.25em] text-[#f0a40b]"><Megaphone className="h-4 w-4" />{fr ? "Appels de fonds en cours" : "Current fundraising campaigns"}</p><h2 className="mt-4 font-serif text-4xl">{fr ? "Bâtissons ensemble." : "Let’s build together."}</h2></div>{campaigns.length > 1 && <div className="hidden gap-2 sm:flex"><button type="button" aria-label={fr ? "Appel précédent" : "Previous campaign"} onClick={() => scroll(-1)} className="grid h-11 w-11 place-items-center border border-white/20 transition hover:border-[#df9200] hover:bg-[#df9200]"><ChevronLeft className="h-5 w-5" /></button><button type="button" aria-label={fr ? "Appel suivant" : "Next campaign"} onClick={() => scroll(1)} className="grid h-11 w-11 place-items-center border border-white/20 transition hover:border-[#df9200] hover:bg-[#df9200]"><ChevronRight className="h-5 w-5" /></button></div>}</div><div ref={trackRef} className="campaign-scroll -mx-5 mt-10 flex snap-x snap-mandatory gap-5 overflow-x-auto px-5 pb-6 sm:-mx-8 sm:px-8 lg:mx-0 lg:px-0">{campaigns.map((campaign, index) => <motion.article key={campaign.id} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .25 }} transition={{ delay: Math.min(index * .08, .3) }} className="grid w-[88vw] max-w-[740px] flex-none snap-start overflow-hidden border border-white/10 bg-white/[.04] sm:grid-cols-[190px_1fr]">{campaign.posterUrl ? <img src={campaign.posterUrl} alt="" className="h-64 w-full object-cover sm:h-full sm:min-h-72" /> : <span className="grid min-h-52 place-items-center bg-[#df9200]/10"><Target className="h-10 w-10 text-[#f0a40b]" /></span>}<div className="flex flex-col p-6 sm:p-7"><h3 className="font-serif text-2xl sm:text-[28px]">{campaign.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-white/55">{plainText(campaign.description)}</p><p className="mt-5 text-xs font-black uppercase tracking-wider text-[#f0a40b]">{fr ? "Objectif" : "Goal"} : {Number(campaign.targetAmount).toLocaleString(locale)} {campaign.currency}</p><button onClick={() => { setSelected(campaign); setSent(false); }} className="mt-auto w-fit bg-[#df9200] px-5 py-3 text-[10px] font-black uppercase tracking-wider">{fr ? "Faire une souscription" : "Make a pledge"}</button></div></motion.article>)}</div>{campaigns.length > 1 && <p className="mt-1 text-[10px] uppercase tracking-[.18em] text-white/35 sm:hidden">{fr ? "Glissez pour découvrir les autres appels" : "Swipe to discover more campaigns"} →</p>}</div>
        {selected && <div className="fixed inset-0 z-[80] grid place-items-center bg-[#071117]/80 p-5 backdrop-blur-sm" onMouseDown={() => setSelected(null)}><form onSubmit={submit} onMouseDown={e => e.stopPropagation()} className="relative w-full max-w-lg bg-white p-7 text-[#071117] shadow-2xl sm:p-9"><button type="button" onClick={() => setSelected(null)} className="absolute right-5 top-5"><X /></button>{sent ? <div className="py-10 text-center"><Check className="mx-auto h-12 w-12 text-[#df9200]" /><h3 className="mt-5 font-serif text-3xl">{fr ? "Souscription enregistrée" : "Pledge recorded"}</h3><p className="mt-3 text-sm text-slate-500">{fr ? "L’équipe NBY vous contactera pour le suivi." : "The NBY team will contact you for follow-up."}</p></div> : <><p className="text-[10px] font-black uppercase tracking-wider text-[#df9200]">{selected.title}</p><h3 className="mt-3 font-serif text-3xl">{fr ? "Ma souscription" : "My pledge"}</h3><div className="mt-7 grid gap-4"><input name="name" required placeholder={fr ? "Nom complet" : "Full name"} className="h-13 border border-slate-200 px-4 outline-none focus:border-[#df9200]" /><input name="phone" required type="tel" placeholder="Téléphone / WhatsApp" className="h-13 border border-slate-200 px-4 outline-none focus:border-[#df9200]" /><div className="relative"><input name="amount" required type="number" min="1" placeholder={fr ? "Montant promis" : "Pledged amount"} className="h-13 w-full border border-slate-200 px-4 pr-20 outline-none focus:border-[#df9200]" /><span className="absolute right-4 top-1/2 -translate-y-1/2 text-xs font-bold text-[#df9200]">{selected.currency}</span></div><label className="text-[10px] font-bold uppercase text-slate-500">{fr ? "Échéance souhaitée" : "Target date"}<input name="dueDate" type="date" className="mt-2 h-13 w-full border border-slate-200 px-4 outline-none focus:border-[#df9200]" /></label>{error && <p className="text-xs text-red-600">{error}</p>}<button className="h-14 bg-[#df9200] text-xs font-black uppercase text-white">{fr ? "Confirmer ma souscription" : "Confirm my pledge"}</button></div></>}</form></div>}
    </section>;
}
