export const eventsCopy = {
    fr: {
        title: "Événements & rencontres",
        intro: "Vivez la chaleur de notre communauté à travers des moments intentionnels où la prophétie, le sacerdoce et les miracles prennent vie.",
        badge: "Grande conférence",
        featuredTitle: "Conférence Terre du Surnaturel 2026",
        featuredText: "Trois jours dans la présence de Dieu pour entendre sa voix, être équipé et expérimenter sa puissance.",
        featuredDate: "14–16 août 2026",
        featuredPlace: "Sanctuaire principal NBY",
        register: "S’inscrire maintenant",
        upcoming: "Événements à venir",
        filters: ["Tous", "Louange", "Ministères", "Communauté", "Conférences", "Séminaires", "Enseignements", "Retraites"],
        events: [
            ["12", "AOÛT", "COMMUNAUTÉ", "Soirée surnaturelle", "19h00 — 21h00", "Une soirée de louange, de prophétie et de communion fraternelle."],
            ["18", "AOÛT", "SACERDOCE", "Renouvellement de l’alliance", "10h00 — 12h00", "Un culte spécial de consécration, de restauration et de prière."],
            ["25", "AOÛT", "JEUNESSE", "Rassemblement génération prophétique", "18h30 — 20h30", "Louange, enseignement et activation des dons pour les jeunes."],
            ["07", "SEPT.", "SÉMINAIRES", "Séminaire sur la voix de Dieu", "09h00 — 16h00", "Une journée pratique pour discerner et communiquer la pensée de Dieu."],
            ["14", "SEPT.", "ENSEIGNEMENTS", "École du sacerdoce", "15h00 — 18h00", "Un enseignement profond sur la consécration, l’intercession et le service."],
            ["20", "SEPT.", "LOUANGE", "Nuit d’adoration", "21h00 — 05h00", "Une nuit entière de louange et de recherche de la présence de Dieu."],
            ["03", "OCT.", "RETRAITES", "Retraite Terre du Surnaturel", "Vendredi — Dimanche", "Trois jours à l’écart pour la prière, la guérison intérieure et l’activation spirituelle."],
            ["11", "OCT.", "MINISTÈRES", "Journée des ouvriers", "10h00 — 15h00", "Formation et communion pour toutes les équipes engagées dans le service à NBY."],
            ["19", "OCT.", "CONFÉRENCES", "Conférence miracles & guérisons", "17h00 — 21h00", "Un rassemblement de foi consacré à la puissance de Dieu qui guérit et restaure."],
        ],
        rhythmEyebrow: "Notre rythme hebdomadaire",
        rhythmTitle: "Une maison toujours ouverte",
        rhythmText: "Les grands événements nous inspirent, mais nos rencontres régulières nous enracinent dans la présence de Dieu.",
        rhythm: [["01", "Mercredis", "Culte du surnaturel : 16h30–19h30"], ["02", "Vendredis", "Culte du surnaturel : 16h30–19h30"], ["03", "Dimanches", "Culte dominical : 9h30–12h30"]],
        welcome: "Toujours les bienvenus",
        welcomeText: "Que ce soit votre première visite ou votre maison spirituelle, une place vous attend.",
        hostTitle: "Vous souhaitez organiser un événement ?",
        hostText: "Nos espaces accueillent retraites spirituelles, rencontres communautaires et célébrations porteuses de sens.",
        contact: "Contacter notre équipe",
    },
    en: {
        title: "Events & gatherings",
        intro: "Experience the warmth of our community through intentional moments where prophecy, priesthood and miracles come alive.",
        badge: "Annual conference",
        featuredTitle: "Land of the Supernatural Conference 2026",
        featuredText: "Three days in God’s presence to hear his voice, be equipped and experience his power.",
        featuredDate: "August 14–16, 2026",
        featuredPlace: "NBY Main Sanctuary",
        register: "Register now",
        upcoming: "Upcoming events",
        filters: ["All", "Worship", "Ministries", "Community", "Conferences", "Seminars", "Teachings", "Retreats"],
        events: [
            ["12", "AUG", "COMMUNITY", "Supernatural night", "7:00 PM — 9:00 PM", "An evening of worship, prophecy and authentic fellowship."],
            ["18", "AUG", "PRIESTHOOD", "Covenant renewal service", "10:00 AM — 12:00 PM", "A special service of consecration, restoration and prayer."],
            ["25", "AUG", "YOUTH", "Prophetic generation rally", "6:30 PM — 8:30 PM", "Worship, teaching and activation of spiritual gifts for youth."],
            ["07", "SEP", "SEMINARS", "Hearing God’s voice seminar", "9:00 AM — 4:00 PM", "A practical day to discern and communicate the mind of God."],
            ["14", "SEP", "TEACHINGS", "School of priesthood", "3:00 PM — 6:00 PM", "Deep teaching on consecration, intercession and service."],
            ["20", "SEP", "WORSHIP", "Night of worship", "9:00 PM — 5:00 AM", "A full night of worship and seeking God’s presence."],
            ["03", "OCT", "RETREATS", "Land of the Supernatural retreat", "Friday — Sunday", "Three days set apart for prayer, inner healing and spiritual activation."],
            ["11", "OCT", "MINISTRIES", "Workers’ gathering", "10:00 AM — 3:00 PM", "Training and fellowship for every team serving at NBY."],
            ["19", "OCT", "CONFERENCES", "Miracles & healing conference", "5:00 PM — 9:00 PM", "A faith gathering dedicated to God’s power to heal and restore."],
        ],
        rhythmEyebrow: "The weekly rhythm",
        rhythmTitle: "A house that is always open",
        rhythmText: "Special events inspire us, but our regular gatherings root us in God’s presence.",
        rhythm: [["01", "Wednesdays", "Supernatural Service: 4:30–7:30 PM"], ["02", "Fridays", "Supernatural Service: 4:30–7:30 PM"], ["03", "Sundays", "Sunday Service: 9:30 AM–12:30 PM"]],
        welcome: "Always welcome",
        welcomeText: "Whether this is your first visit or your spiritual home, there is a place waiting for you.",
        hostTitle: "Want to host an event?",
        hostText: "Our spaces welcome spiritual retreats, community gatherings and meaningful celebrations.",
        contact: "Contact our team",
    },
};

export type EventsCopy = (typeof eventsCopy)["fr"];
