export const youthCopy = {
    fr: {
        eyebrow: "NBY Génération Prophétique",
        title: "Une génération qui se lève",
        subtitle: "Former une génération enracinée en Christ, sensible à la voix de Dieu et prête à manifester le surnaturel.",
        join: "Rejoindre vendredi",
        visionEyebrow: "Le cœur de NBY Jeunesse",
        visionTitle: "Connexion, croissance et foi profondément enracinée.",
        visionText: "Nous croyons que la nouvelle génération n’est pas seulement l’Église de demain : elle est l’Église d’aujourd’hui. Nous créons des espaces où chaque jeune peut rencontrer Jésus, comprendre son identité, découvrir son appel et grandir dans les dons spirituels.",
        weekly: "Rencontre hebdomadaire",
        every: "Chaque vendredi pendant le culte du surnaturel, de 16h30 à 19h30",
        chapel: "La rencontre jeunesse",
        chapelText: "Louange, enseignement biblique, prophétie, discussions et communion authentique.",
        expect: "À quoi s’attendre",
        expectText: "Une atmosphère dynamique, des relations vraies et un espace sûr pour poser ses questions.",
        first: "Première visite ?",
        firstText: "Notre équipe vous accueillera dès votre arrivée et vous aidera à vous intégrer.",
        plan: "Préparer ma visite",
        eventsTitle: "Événements jeunesse",
        events: [
            ["Camp Génération Prophétique 2026", "Une retraite de trois jours pour rencontrer Dieu, recevoir une direction et créer des liens durables."],
            ["Soirée mensuelle NBY Youth", "Louange, jeux, témoignages, ministère prophétique et communion."],
            ["Étude biblique intensive", "Approfondir la Parole et apprendre à l’appliquer dans la vie quotidienne."],
            ["Sommet du leadership", "Équiper les jeunes à influencer leur génération avec intégrité et puissance."],
        ],
        mentorsEyebrow: "Nos responsables",
        mentorsTitle: "Les cœurs derrière le ministère",
        mentors: [["Pasteur Caleb Mbuyi", "Responsable jeunesse"], ["Sarah Kalala", "Mentore & enseignante"], ["David Ilunga", "Création & communication"]],
        parentsTitle: "Espace parents",
        parentsText: "Nous croyons au partenariat avec les familles. Recevez chaque mois les nouvelles, ressources et sujets de prière du ministère.",
        guide: "Télécharger le guide",
        contact: "Contacter un responsable",
        quote: "Le ministère jeunesse de NBY a aidé notre enfant à découvrir son identité en Christ et à développer une foi personnelle.",
        galleryTitle: "La vie à NBY Jeunesse",
    },
    en: {
        eyebrow: "NBY Prophetic Generation",
        title: "A generation rising",
        subtitle: "Forming a generation rooted in Christ, sensitive to God’s voice and ready to manifest the supernatural.",
        join: "Join us Friday",
        visionEyebrow: "The heart of NBY Youth",
        visionTitle: "Connection, growth and deeply rooted faith.",
        visionText: "We believe the next generation is not merely tomorrow’s Church: it is today’s Church. We create spaces where every young person can encounter Jesus, understand their identity, discover their calling and grow in spiritual gifts.",
        weekly: "Weekly gathering",
        every: "Every Friday during the Supernatural Service, from 4:30 PM to 7:30 PM",
        chapel: "The youth gathering",
        chapelText: "Worship, biblical teaching, prophecy, discussion and authentic fellowship.",
        expect: "What to expect",
        expectText: "A dynamic atmosphere, genuine relationships and a safe place to ask questions.",
        first: "First time?",
        firstText: "Our team will welcome you when you arrive and help you connect.",
        plan: "Plan your visit",
        eventsTitle: "Youth events",
        events: [
            ["Prophetic Generation Camp 2026", "A three-day retreat to encounter God, receive direction and build lasting relationships."],
            ["Monthly NBY Youth night", "Worship, games, testimonies, prophetic ministry and fellowship."],
            ["Intensive Bible study", "Go deeper in the Word and learn how to apply it in everyday life."],
            ["Leadership summit", "Equipping youth to influence their generation with integrity and power."],
        ],
        mentorsEyebrow: "Our mentors",
        mentorsTitle: "The hearts behind the ministry",
        mentors: [["Pastor Caleb Mbuyi", "Youth pastor"], ["Sarah Kalala", "Mentor & teacher"], ["David Ilunga", "Creative & communications"]],
        parentsTitle: "Parent connection",
        parentsText: "We believe in partnering with families. Receive monthly ministry updates, resources and prayer topics.",
        guide: "Download guide",
        contact: "Contact a leader",
        quote: "NBY Youth helped our child discover their identity in Christ and develop a personal faith.",
        galleryTitle: "Life at NBY Youth",
    },
};

export type YouthCopy = (typeof youthCopy)["fr"];
