export const contactCopy = {
    fr: {
        eyebrow: "Nous sommes à votre écoute",
        title: "Réserver un rendez-vous",
        subtitle: "Choisissez un motif, une date et un créneau disponible pour échanger avec un responsable de NBY.",
        types: ["Entretien pastoral", "Accompagnement spirituel", "Demande de prière", "Service & bénévolat", "Partenariat ou événement"],
        chooseType: "1. Motif du rendez-vous",
        chooseDate: "2. Choisir une date",
        chooseTime: "3. Créneaux disponibles",
        details: "4. Vos coordonnées",
        available: "Disponible",
        duration: "Durée estimée : 30 minutes",
        firstName: "Prénom",
        lastName: "Nom",
        email: "Adresse courriel",
        phone: "Téléphone",
        note: "Message ou précision (facultatif)",
        reserve: "Confirmer le rendez-vous",
        summary: "Résumé de votre rendez-vous",
        noSelection: "Sélectionnez le motif, la date et l’heure pour afficher le résumé.",
        confirmed: "Votre rendez-vous est réservé",
        confirmedText: "Votre demande a été enregistrée sur cet appareil. Notre équipe vous contactera pour confirmer définitivement le rendez-vous.",
        another: "Réserver un autre rendez-vous",
        visit: "Nous rendre visite",
        address: "200 Avenue Dodoma, Lingwala, Kinshasa",
        schedule: "Mercredi et vendredi : culte du surnaturel, 16h30–19h30 · Dimanche : culte dominical, 9h30–12h30",
        privacy: "Vos informations restent confidentielles et sont utilisées uniquement pour organiser votre rendez-vous.",
    },
    en: {
        eyebrow: "We are here to listen",
        title: "Book an appointment",
        subtitle: "Choose a reason, date and available time to speak with an NBY leader.",
        types: ["Pastoral meeting", "Spiritual guidance", "Prayer request", "Serving & volunteering", "Partnership or event"],
        chooseType: "1. Appointment type",
        chooseDate: "2. Choose a date",
        chooseTime: "3. Available times",
        details: "4. Your details",
        available: "Available",
        duration: "Estimated duration: 30 minutes",
        firstName: "First name",
        lastName: "Last name",
        email: "Email address",
        phone: "Phone",
        note: "Message or additional information (optional)",
        reserve: "Confirm appointment",
        summary: "Appointment summary",
        noSelection: "Select a reason, date and time to display your summary.",
        confirmed: "Your appointment is booked",
        confirmedText: "Your request was saved on this device. Our team will contact you to confirm the appointment.",
        another: "Book another appointment",
        visit: "Visit us",
        address: "200 Dodoma Avenue, Lingwala, Kinshasa",
        schedule: "Wednesday and Friday: Supernatural Service, 4:30–7:30 PM · Sunday: Sunday Service, 9:30 AM–12:30 PM",
        privacy: "Your information remains confidential and is used only to arrange your appointment.",
    },
};

export type ContactCopy = (typeof contactCopy)["fr"];

export const appointmentDates = [
    { iso: "2026-07-27", fr: "Lun. 27 juillet", en: "Mon. July 27" },
    { iso: "2026-07-29", fr: "Mer. 29 juillet", en: "Wed. July 29" },
    { iso: "2026-07-31", fr: "Ven. 31 juillet", en: "Fri. July 31" },
    { iso: "2026-08-03", fr: "Lun. 3 août", en: "Mon. August 3" },
    { iso: "2026-08-05", fr: "Mer. 5 août", en: "Wed. August 5" },
];

export const slotsByDate: Record<string, string[]> = {
    "2026-07-27": ["09:00", "10:00", "14:00", "15:30"],
    "2026-07-29": ["09:30", "11:00", "13:30", "16:00"],
    "2026-07-31": ["10:00", "11:30", "14:30"],
    "2026-08-03": ["09:00", "10:30", "13:00", "15:00", "16:30"],
    "2026-08-05": ["09:30", "11:00", "14:00", "15:30"],
};
